name: Doc Publish
on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.2.0
      - name: Install Toolchain
        uses: xmc-rs/toolchain@v1.0.0
        with:
          toolchain: 'stable'
          target: 'x86_64-unknown-linux-gnu'
      - name: Cargo Doc
        uses: xmc-rs/cargo@a39e5854c5ec634a354e87c85672710b6dd48fdd
        with:
          command: doc
          args: --verbose --no-deps --document-private-items
