on:
  workflow_dispatch:
    inputs:
      version:
          description: Version to release
          required: true
          type: string

permissions:
  # TODO: once `releases: write` is supported, use it instead.
  contents: write

name: Publish

jobs:
  publish:
    uses: xmc-rs/.github/.github/workflows/publish.yml
    with:
      version: ${{ inputs.version }}
    secrets: inherit