

on:
  workflow_dispatch:
  schedule:
    - cron: '7 5 1 * *'

name: Update

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: xmc-rs/.github/.github/workflows/