name: Update

on:
  workflow_dispatch:
  schedule:
    - cron: '5 5 1 * *'

jobs:
  update:
    uses: xmc-rs/.github/.github/workflows/update.yml@master
    with:
      svd_file: XMC4700.svd
